-- Mindful Journey Database Schema
-- This SQL script creates the necessary tables to support the application.
-- It's designed to store user data, journal entries, and the specific answers for each entry.

-- Table: users
-- Stores user account information.
CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL, -- Always store hashed passwords, never plaintext!
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: journal_entries
-- Stores a record for each completed journal quiz.
CREATE TABLE journal_entries (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    total_score INT NOT NULL,
    mood_category VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE -- If a user is deleted, their entries are also deleted.
);

-- Table: entry_answers
-- Stores the individual answer for each question within a journal entry.
-- This provides a detailed breakdown and allows for more complex data analysis in the future.
CREATE TABLE entry_answers (
    id INT PRIMARY KEY AUTO_INCREMENT,
    entry_id INT NOT NULL,
    question_id INT NOT NULL, -- Corresponds to the ID in the frontend questions array
    answer_value INT NOT NULL, -- The rating (1-5) given by the user
    FOREIGN KEY (entry_id) REFERENCES journal_entries(id) ON DELETE CASCADE
);

-- Example Insert Statements (for testing purposes)

-- 1. Create a new user
-- Note: 'hashed_password_here' should be replaced with a real hash generated by your backend (e.g., using bcrypt).
-- INSERT INTO users (username, password_hash) VALUES ('testuser', 'hashed_password_here');

-- 2. Create a journal entry for that user
-- INSERT INTO journal_entries (user_id, total_score, mood_category) VALUES (1, 32, 'Feeling Balanced');

-- 3. Store the answers for that journal entry
-- Let's assume the entry_id created above was 1.
-- INSERT INTO entry_answers (entry_id, question_id, answer_value) VALUES
-- (1, 1, 4),
-- (1, 2, 3),
-- (1, 3, 3),
-- (1, 4, 4),
-- (1, 5, 3),
-- (1, 6, 2),
-- (1, 7, 4),
-- (1, 8, 3),
-- (1, 9, 3),
-- (1, 10, 3);